move session manager to service
InfiniTensor/InfiniLM pull request #11
Opened 2024-07-04 09:09 UTC by qinyiqun

2024-07-04 10:00 UTC, YdrMaster requested changes

2024-07-04 10:00 UTC, YdrMaster commented on web-api/src/response.rs
>  //! All HttpResponses in this App.
这个文件完全不用改

2024-07-05 02:50 UTC, YdrMaster requested changes

2024-07-05 02:50 UTC, YdrMaster commented on web-api/src/manager.rs
>              capacity.map(|c| NonZeroUsize::new(c).expect("Session capacity must be non-zero"));
Manager 本来就是要 `Option<usize>` 怎么会先 `Nonzero` 再取回去

2024-07-05 02:50 UTC, YdrMaster commented on web-api/src/manager.rs
> +                    .get_or_insert(session_id.clone(), || self.service.launch());
为啥不是 `?`

2024-07-05 02:50 UTC, YdrMaster commented on web-api/src/manager.rs
> +                let session_result = self.session_manager.take(&session_id);
同上

2024-07-05 02:50 UTC, YdrMaster commented on web-api/src/manager.rs
> +                let session_result = self
同上

2024-07-05 02:50 UTC, YdrMaster commented on web-api/src/manager.rs
> +        let result = self.session_manager.fork(session_id_, new_session_id_);
同上

2024-07-05 02:50 UTC, YdrMaster commented on web-api/src/manager.rs
> +        let result = self.drop_with_session_id(SessionId::Permanent(session_id));
同上

2024-07-05 03:05 UTC, qinyiqun commented on web-api/src/manager.rs
>              capacity.map(|c| NonZeroUsize::new(c).expect("Session capacity must be non-zero"));
看起来是为了防止capacity为0

2024-07-05 03:06 UTC, qinyiqun commented on web-api/src/manager.rs
> +                    .get_or_insert(session_id.clone(), || self.service.launch());
这里传入的错误是SessionError，传出的错误是Error，如果使用？的话需要一个From函数做变换

2024-07-05 06:03 UTC, YdrMaster requested changes

2024-07-05 06:03 UTC, YdrMaster commented on web-api/src/manager.rs
>      fn restore(&self, session_id: &SessionId, session: Session<M>) {
这个没必要单写了，手工内联进去吧

2024-07-05 06:03 UTC, YdrMaster commented on web-api/src/manager.rs
> +        let session_id_ = SessionId::Permanent(session_id.clone());
这个为啥要 clone？直接 shadow 原来的名字就行了

2024-07-05 08:41 UTC, YdrMaster approved these changes

2024-07-05 08:41 UTC, merged