添加 android generate
InfiniTensor/InfiniLM pull request #20
Opened 2024-08-12 02:54 UTC by ma-hang

2024-08-12 03:36 UTC, YdrMaster requested changes

2024-08-12 03:36 UTC, YdrMaster commented on android/src/channels.rs
> +    Generate(String, Sender<String>, usize),
ui 上不用这样设置 max-steps，因为 ui 可以随时并发停止

2024-08-12 03:39 UTC, ma-hang commented on android/src/channels.rs
> +    Generate(String, Sender<String>, usize),
嗯嗯

2024-08-12 04:00 UTC, YdrMaster commented
格式检查不过，cargo fmt 全部格式化，这些修改用 git commit --amend + git push -f 提交

2024-08-12 04:36 UTC, YdrMaster requested changes

2024-08-12 04:36 UTC, YdrMaster commented on android/src/lib.rs
> +pub extern "system" fn Java_org_infinitensor_lm_Native_startgenerate(
这个按 java 命名风格来命名，小驼峰：startGenerate

2024-08-12 04:36 UTC, YdrMaster commented on android/src/lib.rs
> +fn dispatch(model_dir: PathBuf, mut requests_receiver: UnboundedReceiver<TaskRequest>) {
这个叫做 requests 就行了，一般没必要加 receiver，就好像 i32 一般不加 i32 一样

2024-08-12 04:36 UTC, YdrMaster commented
新增接口同时改一下 README.md

2024-08-12 04:38 UTC, ma-hang commented on android/src/lib.rs
> +pub extern "system" fn Java_org_infinitensor_lm_Native_startgenerate(
嗯嗯

2024-08-12 04:39 UTC, ma-hang commented on android/src/lib.rs
> +fn dispatch(model_dir: PathBuf, mut requests_receiver: UnboundedReceiver<TaskRequest>) {
嗯嗯

2024-08-12 12:42 UTC, YdrMaster requested changes

2024-08-13 01:31 UTC, ma-hang commented on android/src/lib.rs
> +                    if generator.is_none() {
嗯嗯

2024-08-13 03:51 UTC, YdrMaster approved these changes

2024-08-13 09:18 UTC, merged