fix(service): 输入超长截取时会保留一段起始的部分，防止在对话时超长截取后胡说
InfiniTensor/InfiniLM pull request #7
Opened 2024-06-11 11:19 UTC by pwhMass

还需进一步测试

2024-06-24 01:24 UTC, YdrMaster commented on common/src/lib.rs
> +pub mod vec_slice_range;
这个 slice 不是 service 特供吗，为啥移到 common？

2024-06-24 01:24 UTC, YdrMaster commented on common/src/vec_slice_range.rs
> +//!  多切片可间断range
这个模块就一个结构定义，模块级文档通常没什么意义。我知道这个是为了过 missing docs，可以留空。另外这个东西感觉挺常见的，可以看看有没有库

2024-06-24 01:24 UTC, YdrMaster commented on common/src/vec_slice_range.rs
> +    pub fn try_from(v: impl IntoIterator<Item = Range<usize>>) -> Option<Self> {
返回 None 有点怪，其实直接崩溃也没啥问题，或者干脆允许任意顺序输入，自动重排

2024-06-24 01:24 UTC, YdrMaster commented on common/src/vec_slice_range.rs
> +    pub fn get_ranges(&self) -> &Vec<Range<usize>> {
这个应该返回切片，Vec 的不可变引用没有什么意义

2024-06-24 01:24 UTC, YdrMaster commented on service/src/session/cache.rs
> +use std::usize;
这是啥

2024-06-24 16:10 UTC, pwhMass commented on common/src/vec_slice_range.rs
> +//!  多切片可间断range
找到了一个库 [https://crates.io/crates/slice-utils](slice-utils)，但是研究之后感觉用这个库开销太大了，我们需要对`Cache<Storage>`的`tokens: Vec<utok>`和`cached: VecSliceRange`进行频繁的操作，所以用这个库似乎不太合适。
另一种方法是将`tokens`和`cached`绑在一起，这样两者一起操作防止遗漏，但这样想的话似乎`cache`也得跟前两者绑到一起，但由于`cache: Tensor<Storage>`这种类型，不知如何操作。

2024-06-24 16:28 UTC, pwhMass commented on common/src/vec_slice_range.rs
> +    pub fn get_ranges(&self) -> &Vec<Range<usize>> {
```rust
/// 重置缓存窗口，保留起始的一部分，并将起始点设置为尾部一部分之前
    pub fn reset_within_start_and_end_range(
        &mut self,
        start_size: usize,
        end_size: usize,
        max: usize,
    ) {
        if self.tokens.len() - self.cached.end() + self.cached.len() >= max {
            let ranges = self.cached.get_ranges();
            let mut first_range = ranges.first().unwrap().clone();
            first_range.end = min(first_range.end, start_size);

            self.cached = VecSliceRange::try_from(vec![
                first_range,
                (self.tokens.len() - end_size..self.tokens.len() - end_size),
            ])
            .unwrap();
        }
    }
```

`get_ranges`就是用作获取cache部分在tokens中的位置的，比如`reset_within_start_and_end_range`就是根据原先的位置来生成新的`VecSliceRange`

2024-06-24 16:34 UTC, pwhMass commented on service/src/session/cache.rs
> +use std::usize;
use std::cmp::min 是没必要用吗？
use std::usize 的确是多加了

2024-06-25 02:49 UTC, YdrMaster requested changes

2024-06-25 02:49 UTC, YdrMaster commented on service/src/session/vec_slice_range.rs
> +use std::{ops::Range, usize};
这里不是还有 `std::usize` 么😂

2024-06-25 02:49 UTC, YdrMaster commented on service/src/session/vec_slice_range.rs
> +        let mut result = Vec::new();
呃，这个应该是 `.into_iter().collect::<Vec<_>>()` 的意思？

2024-06-25 02:49 UTC, YdrMaster commented on service/src/session/vec_slice_range.rs
> +            .reduce(|a, b| a + b)
Iter 有 `.sum()` 可以直接加

2024-06-25 02:49 UTC, YdrMaster commented on common/src/vec_slice_range.rs
> +    pub fn get_ranges(&self) -> &Vec<Range<usize>> {
就是说所有 `-> &Vec<T>` 都应该可以直接换成 `-> &[T]` 而不引起其他变化，这应该是确定的

2024-06-25 02:49 UTC, YdrMaster commented on service/src/session/vec_slice_range.rs
> +                "extend_to function can't reduce the {:?} end to {:?},so it do nothing",
格式串是可以直接内联标识符的，`{self:?}` `{end:?}` 这样比较好看

2024-06-25 02:56 UTC, YdrMaster commented on common/src/vec_slice_range.rs
> +//!  多切片可间断range
https://crates.io/crates/rangemap 我猜是这个。这个功能的抽象应该是多个“范围”（`Range`）的集合，这个抽象还挺常见的，尤其是 rcore 里有，所以我有印象相关的库有好几个

2024-06-25 05:42 UTC, pwhMass commented on service/src/session/vec_slice_range.rs
> +        let mut result = Vec::new();
是这样的没错，就是加了一个递增检验

2024-06-26 01:34 UTC, YdrMaster requested changes

2024-06-26 01:34 UTC, YdrMaster commented on service/src/session/vec_slice_range.rs
> +        let mut result = Vec::new();
这样一个一个 push 不如先 to_vec 下来再检验……无论是可读性上还是性能上。其实这种反正一进来就要 to_vec 的不如直接要求传 Vec

2024-07-06 00:50 UTC, YdrMaster approved these changes

2024-07-06 00:50 UTC, YdrMaster commented on service/Cargo.toml
> +rangemap = { version = "1"  }
rangemap = "1.5"

2024-07-06 00:50 UTC, merged